# -*- coding: utf-8 -*-
"""calcular_aumentos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6Lf6iz6girzvLazeWb0uUbz6IEQK1Q8
"""

def multiplicar100 (a):
  return a * 100

def dividir (resultado, divisor):
  if divisor == 0:
      return "Error: No se puede dividir por cero."
  return resultado / divisor

def restar100 (a):
  return a - 100


def calcular_porcentajes():
  print ("CALCULADORA DE AUMENTOS Y DISMINUCIONES")
  print ("¿Quéres saber que porcentaje aumento o disminuyo?")

  try:
        num1 = float(input("Introduce el precio actual: "))
        resultado_multiplicacion = multiplicar100(num1)
        print("Ok!")

        num2 = float(input("Ahora introduce el precio que pagabas antes:"))
        resultado_divison = dividir(resultado_multiplicacion, num2)
        print("Ok!")

        resultado_final = restar100(resultado_divison)

        if resultado_final < 0:
          print(f"Tuvo una disminucion del {round(abs(resultado_final), 2)}% ")
        else:
          print(f"Tuvo un aumento del {round (resultado_final, 2)}%")

  except ValueError:
        print("Por favor, introduce un número válido.")

calcular_porcentajes()